Hw7
Mamalazer/niffler-st4 pull request #3
Opened 2024-01-30 16:57 UTC by Mamalazer

1) Create methods 'updateInAuthById', 'updateInUserDataById', 'selectUserInfoFromAuthById' and 'selectUserInfoFromUserDataById' in UserRepository; 
2) create realisations for methods 'deleteInAuthById', 'deleteInUserdataById', 'updateInAuthById, 'updateInUserDataById', 'selectUserInfoFromAuthById' and 'selectUserInfoFromUserDataById' in UserRepositoryJdbc;
3) create annotation DbUser; 
4) create model UserAuthInfo; 
5) create UserCreateExtension

2024-02-02 07:52 UTC, sashkir7 requested changes
Нужно обратить внимание на то, что хранить мутабельные данные, как свойство extension-класса нельзя

2024-02-02 07:52 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +              PreparedStatement friendsPs = conn.prepareStatement("DELETE FROM friendship WHERE user_id = ?");
Круто, что не забыли про друзей!

2024-02-02 07:52 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +                      "UPDATE \"authority\" SET authority = ? where id = ?"
Здесь лучше сделать немного иначе. Самый простой способ:
- сначала удаляем все права для данного пользователя
- инсертим новые права

2024-02-02 07:52 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +            switch (authoritySet.getString("authority")) {
У enum есть такой static-метод, как valueOf(). Можно воспользоваться им

2024-02-02 07:52 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +                throw new IllegalStateException("Unknown currency value");
Аналогично (valueOf)

2024-02-02 07:52 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/user/UserCreateExtension.java
> +    private List<String> actualUsers = new ArrayList<>();
В extension на уровне класса нельзя хранить мутабельные данные (то есть данные, которые в процессе работы изменяются). Почему?
Потому что Junit создает единственный экземпляр данного extension-класса. Соответственно, при параллельном запуске тестов возможны конфликты, когда с разных потоков перетираем одно и тоже значение. Отследить такую проблему очень тяжело.

Для этих целей используется store, который мы успешно применяли на первых лекциях. Через него можно "безопасно" передавать данные. 

Еще раз: передавать (+хранить) мутабельные данные через свойства extension-класса нельзя. Это важно

2024-02-02 07:52 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/user/UserCreateExtension.java
> +            String password = method.getAnnotation(DbUser.class).password();
Чтобы два раза не писать method.getAnnotation(DbUser.class) - лучше шагом выше вынести ее в переменную

2024-02-02 07:52 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/page/MainPage.java
> +    }
Очень спорное решение.
При создании экземпляра класса вызывать конструктор, в рамках которого проверяется, что данная страница успешно загружена. 
Лучше оставить пустой конструктор (по умолчанию), а проверять через метод shouldBeLoaded()

2024-02-02 08:02 UTC, Mamalazer commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +                      "UPDATE \"authority\" SET authority = ? where id = ?"
Зачем, что это даст?

2024-02-02 09:22 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/db/repository/UserRepositoryJdbc.java
> +                      "UPDATE \"authority\" SET authority = ? where id = ?"
Сначала показалось, что в качестве фильтрации используете id пользователя.
Вы же используете id самой сущности - так тоже можно реализовать.

2024-02-04 10:32 UTC, sashkir7 approved these changes

2024-02-04 10:32 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/page/MainPage.java
> +    public MainPage checkThatMainPageLoaded() {
Можно просто checkIsLoaded()
Метод мы вызываем у экземпляра класса MainPage, поэтому из контекста понятно, что речь идет именно про главную страницу

2024-02-05 16:54 UTC, merged